#ifndef AUXILIARY_MATH_LIBRARY_FOR_GAME_DEVELOPMENT_LIBRARY_H
#define AUXILIARY_MATH_LIBRARY_FOR_GAME_DEVELOPMENT_LIBRARY_H

void hello();

int add(int a, int b);
#endif  // AUXILIARY_MATH_LIBRARY_FOR_GAME_DEVELOPMENT_LIBRARY_H