name: C++ CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install CMake and g++
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      - name: Configure and Build
        run: |
          cmake -S . -B build
          cmake --build build

      - name: Run tests
        run: cd build && ctest
